[package]
name        = "roadboard-storage"
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true

[dependencies]
roadboard-core = { path = "../core" }
sqlx           = { workspace = true }
serde          = { workspace = true }
thiserror      = { workspace = true }
tokio          = { workspace = true }

[lints]
workspace = true
