[package]
name        = "robot"
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true

[dependencies]
anyhow    = { workspace = true }
clap      = { workspace = true }
toml_edit = { workspace = true }
serde_json = { workspace = true }
regex     = { workspace = true }
chrono    = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
